<?
/*
NOTICE: Do not edit this file to put in your username and password. Rather, create a file called local_settings.php in this directory and fill it with your settings.

For a mysql setup, the file should look something like:

<?
return array(
	'contact_name' => 'Your Bungie.net User Name',
	'mysql' => array (
		'host' => 'localhost',
		'db' => 'ustalk',
		'username' => 'ustalk',
		'password' => '8LPTtx022STbXhy2a'
	)
);
?>

*/

$defaults = array(
	'contact_name' => 'jmh9072',
);

$local_settings = array();
if (file_exists('local_settings.php')) {
	$local_settings = include 'local_settings.php';
	if(!is_array($local_settings))
		die('Local settings file MUST return an array.');
}
$settings = array_merge($defaults, $local_settings);

//connect to db
if(array_key_exists('mysql', $settings)) {
	$db = @mysql_connect($settings['mysql']['host'], $settings['mysql']['username'], $settings['mysql']['password']);

	if(mysql_errno()) {
		print(mysql_errno());
		die("Error connecting to database, contact ".$settings['contact_name']." immediately");
	}

	mysql_select_db($settings['mysql']['db']);
} else {
	die('You must provide a local settings file telling ustalk what mysql server to connect to. At the moment no other databases are supported.');
}
?>
