<?
/*
NOTICE: Do not edit this file to put in your username and password. Rather, create a file called local_settings.php in this directory and fill it with your settings.

For a mysql setup, the file should look something like:

<?
return array(
	'contact_name' => 'Your Bungie.net User Name',
	'mysql' => array (
		'host' => 'localhost',
		'db' => 'ustalk',
		'username' => 'ustalk',
		'password' => '8LPTtx022STbXhy2a'
	)
);
?>

*/

$defaults = array(
	'contact_name' => 'jmh9072',
);

$local_settings = array();
if (file_exists('local_settings.php')) {
	$local_settings = include 'local_settings.php';
	if(!is_array($local_settings))
		die('Local settings file MUST return an array.');
}
return array_merge($defaults, $local_settings);
?>
